# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the production build files to the working directory
COPY build/ .

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the app
CMD ["npx", "serve", "-s", ".", "-l", "3000"]
